import { expect, test } from '@playwright/test'

test('a learner can complete a lesson and keep progress after reload', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'Begin course' }).click()
  await expect(page.getByRole('heading', { name: 'Begin where you are' })).toBeVisible()
  await expect(page.getByText('Original passage')).toBeVisible()
  await page.getByRole('button', { name: 'Mark complete' }).click()
  await expect(page.getByRole('button', { name: 'Completed' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Completed' })).toBeVisible()
})

test('office hours acknowledge an unsupported question', async ({ page }) => {
  await page.goto('/course/marcus-aurelius-meditations/lesson/lesson-3')
  if ((page.viewportSize()?.width ?? 1200) <= 1030) await page.getByRole('tab', { name: 'Ask' }).click()
  await page.getByLabel('Ask a question').fill('What did Marcus think about quantum chromodynamics?')
  await page.getByLabel('Send question').click()
  await expect(page.getByText('Insufficient source evidence')).toBeVisible()
  await expect(page.locator('#lesson-sources').getByRole('button', { name: 'Listen or watch' })).toBeVisible()
})

test('a saved lesson note appears in the notebook', async ({ page }) => {
  await page.goto('/course/marcus-aurelius-meditations/lesson/lesson-1')
  await page.getByRole('tab', { name: 'Notes' }).click()
  await page.getByLabel('Private note').fill('Attention returns through practice.')
  await page.getByRole('button', { name: 'Save note' }).click()
  await expect(page.getByRole('button', { name: 'Saved on this device' })).toBeVisible()
  await page.goto('/notebook')
  await expect(page.getByText('Attention returns through practice.')).toBeVisible()
})

test('a keyless debate exposes both interpretations and a synthesis', async ({ page }) => {
  await page.goto('/debates')
  await page.getByRole('button', { name: 'Stage debate' }).click()
  await expect(page.getByText('Opening arguments')).toBeVisible()
  await expect(page.getByText('AI synthesis')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Listen or watch' })).toHaveCount(6)
})

test('a learner can build a cited course from pasted source text', async ({ page }) => {
  const source = Array.from({ length: 9 }, (_, index) => `Observation ${index + 1} begins with a concrete event and follows how attention changes the result over time. The passage records a specific relationship between evidence, judgment, practice, and revision so that a learner can inspect the claim instead of merely repeating it.`).join('\n\n')
  await page.goto('/create')
  await page.getByLabel('Name').fill('The Field Observer')
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('Or paste text').fill(source)
  await page.getByRole('button', { name: 'Add pasted source' }).click()
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('Learning objective').fill('Learn to make decisions by separating observations from interpretations.')
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByRole('heading', { name: 'Shape the outline.' })).toBeVisible()
  await page.getByRole('button', { name: 'Build course' }).click()
  await expect(page.getByRole('heading', { name: 'Your course is ready to review.' })).toBeVisible()
  await page.getByRole('link', { name: 'Open first lesson' }).click()
  await expect(page.getByText('Original passage')).toBeVisible()
})

test('encrypted credentials can be unlocked after reload', async ({ page }) => {
  await page.goto('/settings')
  await page.getByRole('button', { name: 'OpenAI' }).click()
  await page.getByLabel('API key', { exact: true }).fill('temporary-test-key')
  await page.getByRole('checkbox', { name: 'Remember encrypted keys' }).check()
  await page.getByLabel('Passphrase').fill('test passphrase')
  await page.getByRole('button', { name: 'Save encrypted' }).click()
  await expect(page.getByText('Encrypted credentials saved in this browser.')).toBeVisible()
  await page.reload()
  await page.getByLabel('Passphrase').fill('test passphrase')
  await page.getByRole('button', { name: 'Unlock' }).click()
  await expect(page.getByText('Credentials unlocked for this session.')).toBeVisible()
  await expect(page.getByLabel('API key', { exact: true })).toHaveValue('temporary-test-key')
})

test('keyboard users can skip navigation and open the primary source', async ({ page, context }) => {
  await page.goto('/')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', { name: 'Skip to content' })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('#main-content')).toBeFocused()

  await page.goto('/course/marcus-aurelius-meditations/lesson/lesson-1')
  await page.getByRole('link', { name: 'View source evidence' }).click()
  if ((page.viewportSize()?.width ?? 1200) <= 1030) await expect(page.getByRole('tab', { name: 'Sources' })).toHaveAttribute('aria-selected', 'true')
  const sourceLink = page.getByRole('link', { name: 'Open bundled text' })
  const [sourcePage] = await Promise.all([context.waitForEvent('page'), sourceLink.click()])
  await sourcePage.waitForLoadState('domcontentloaded')
  expect(sourcePage.url()).toContain('/sources/meditations.txt')
  await sourcePage.close()
})

test('media generation shows scope, scripts, and the key requirement before submission', async ({ page }) => {
  await page.goto('/course/marcus-aurelius-meditations/lesson/lesson-1')
  await page.getByRole('button', { name: 'Listen or watch' }).click()
  await expect(page.getByRole('dialog', { name: 'Generate narrated scenes' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Close dialog' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: /Generate \d+ scenes?/ })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Close dialog' })).toBeFocused()
  await page.getByRole('radio', { name: /Avatar \+ captions/ }).click()
  await expect(page.getByText(/portrait will be sent to fal.ai/)).toBeVisible()
  await expect(page.getByText('Validated script sent to the provider')).toBeVisible()
  await page.getByRole('button', { name: /Generate \d+ scenes?/ }).click()
  await expect(page.getByText('Add a fal.ai key in Settings before submitting paid media jobs.')).toBeVisible()
})
